apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-example
  name: deployment-example
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-example
    spec:
      containers:
      - image: quay.io/mwasher/httpbin
        imagePullPolicy: Always
        command: ["gunicorn", "-b", "0.0.0.0:8080", "httpbin:app", "-k", "gevent"]
        name: httpbin
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:                    #############
            cpu: 500m                  #############
            memory: 1G                 #############
            ephemeral-storage: 100M    #############
          limits:                      #############
            cpu: 500m                  #############
            memory: 1G                 #############
            ephemeral-storage: 100M    #############
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:                  #############
        - name: ephemeral              #############
          mountPath: /tmppath          #############
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:                         #############
      - name: ephemeral                #############
        emptyDir: {}                   #############
